import MainText from '@/components/maintext';
import Numbered from '@/components/numbered';
import PolicyItem, { PolicyItemN } from '@/components/policyitem';
import SubText from '@/components/subtext';
import { acceptableItems } from '@/data/acceptablepolicy';
import { protection } from '@/data/protection';
import { substance } from '@/data/substance';
import React from 'react';

const TermsOfService = () => {
	return (
		<div className='container mx-auto'>
			<div className='p-2 m-2'>
				<div className='flex justify-end '>
					<p className='tracking-widest'>Terms of use</p>
				</div>
				<div className='flex justify-center my-6'>
					<p className='uppercase text-center font-bold tracking-widest'>
						terms of use
					</p>
				</div>
				<div className='flex justify-center my-6'>
					<p className='capitalize text-center font-bold tracking-widest'>
						Business Management Platform
					</p>
				</div>
				<div className='my-6'>
					<p className='tracking-widest'>
						We are AGIZO TECH PTY LTD, “Agizo”, [“us, “we”], a company limited
						and registered in Kenya, having a registered address at Bihi Towers
						8th Floor Suite 2 Along Moi Avenue, Nairobi to enable vendors to
						keep tabs on the revenue generated by their business during a
						certain period, monitor upcoming appointments, monitor new client
						intake, client schedules, staff revenue, staff attendance rates,
						sell products, view returning customer rates,, and more through our
						business management platform software as a service [hereinafter
						‘Services’]. There is no need to install any software to use our
						Services, you may access the business management platform from your
						browser.
					</p>
					<p className='tracking-widest'>
						By accessing our Website and Services you acknowledge and accept the
						following terms and conditions. If you disagree, we kindly ask you
						to leave this Website immediately. Please take time to review our
						Privacy Policy, found here. Note, these terms and conditions are
						open to amendment, and we reserve the right to alter and or delete
						these as appropriate and without notice. You must be at least 18
						years of age to create an Account and use the Website.
					</p>
				</div>
				<div className='my-6'>
					<p className='font-bold underline'>Access</p>
					<MainText
						text='1. Please note that you take full responsibility for your
						participation on our Website/ Services. You will be asked to
						register and/or select a Username and password before creating your
						own online merchant profile. All registration information you submit
						to create an account must be accurate and kept up to date. Your
						failure to do so will constitute a breach of these terms, which may
						result in immediate termination of your account. You may not:'
					/>

					<SubText
						text='(i) select or use as a Username a name of another person with the
						intent to impersonate that person; or'
					/>
					<SubText
						text='(ii) use as a Username a name subject to any rights of another
						person without appropriate authorisation.'
					/>
					<MainText
						text='We reserve the right to verify any document, information or
						representation made by you in processing your
						application/membership. We reserve the right to refuse registration
						of, or cancel, a Username, in our sole discretion. If we cancel your
						registration, you agree that you will not create another one or
						otherwise try to access our service(s) without our permission. You
						agree not to sell, transfer, or assign your login/registration or
						any registration rights. It is your responsibility to notify us of
						any changes in such information, including but not limited to your
						contact information. Terms Of Use'
					/>
					<MainText text='2. You are responsible for maintaining the confidentiality of your password and are responsible for all use of your account. It is therefore critical that you do not share your password with anyone. You agree not to use the account, Username, email address or password of another member or subscriber at any time and not to allow any other person to use your account. Your account is not transferable. You agree to notify us immediately if you suspect any unauthorised use of, or access to, your account or password.' />
					<MainText text='3. Access to this Website and or our Services is also conditional that:' />
					<SubText text='i. You accept all terms herein unequivocally.' />
					<SubText text='ii. By engaging with us for a service you are confirming to us that you have reached the age of 18 years.' />
					<SubText
						text='iii. You accept access may be withdrawn at any time without reason.
'
					/>
					<SubText
						text='iv. You acknowledge that by using this Website and or our Services, you accept that we can
show you adverts from our affiliates.'
					/>
					<SubText
						text='v. You accept that we are not responsible for the security of data provided or transmitted
to you via any correspondence or our Website.'
					/>
					<SubText text='vi. You accept access to our Website/Services may be restricted and or be unavailable.' />
					<SubText text='vii. You acknowledge and accept our Website/Services may contain links to other Websites. and we have no control regarding the contents and or access to these sites.' />
					<SubText text='viii. You accept that we are not responsible for any content published by any other user (unless notified thereof).' />
					<SubText text='ix. You acknowledge we may need to update these Terms from time to time to accurately reflect our/your Services and obligations. It is your (the user’s) responsibility to stay up to date on Terms.' />
					<SubText text='x. You accept these Terms do not confer any third-party beneficiary rights.' />
					<SubText
						text='xi. Your merchant account cannot be used for illegality.
'
					/>
					<SubText text='xii. You may create loyalty and reward programs to increase customer retention, subject to relevant consumer legislation.' />
					<SubText text='xiii. You accept that to create a Member Account, Agizo may conduct certain checks and require a User to provide information relevant to any mandatory criteria relevant to the Services to be provided. You agree to provide us with such information or documentation as reasonably requested to do so and authorise Agizo to conduct any such verification checks.' />
				</div>
				<div className='my-6'>
					<p className='font-bold underline'>Engagement</p>
					<MainText text='4. Agizo is a platform that allows you to connect with customers through your online merchant platform. Agizo provides a platform only and does not engage or employ customers or customer service representatives on your behalf. When you trade with a customer, we are not a party to that contract. You enter into this Agreement on the basis that you are an independent company/contractor. We do not employ you or any other person associated with your business. Agizo does not market your Services as a person employed or engaged by Agizo. Nothing in this Agreement or your use of the Website and/or Services is intended to give rise to any such relationship, or any relationship of partnership or joint venture.' />
					<MainText text='5. You acknowledge and agree that Agizo acts only as an intermediary facilitating the provision of selected business transactions and that Agizo has no control over and is not responsible for any acts or omissions of any Users on or off Agizo’s Website and/or Services and/or App.' />
					<MainText
						text='6. When you access our Website and/or Services, you may obtain access to content posted by other Users or third parties. You agree and acknowledge that Agizo provides a platform only, that acts as a forum for venue for online distribution/sales and publication of content, and Agizo does not verify content nor makes any warranties or representations (either express or implied) whatsoever in relation to content, its accuracy, completeness, quality, currency or otherwise, and is not responsible for any content including content posted by others that may include Prohibited Content. Agizo may, but is not obliged to, take any action it considers (in its sole and absolute discretion) appropriate with respect to content that it considers is Prohibited Content, may create liability for Agizo, harm our business operation or reputation, or cause us to lose the Services of its suppliers.
'
					/>
				</div>
				<div className='my-6'>
					<p className='font-bold underline'>Payments / Fees</p>
					<MainText text='7. We offer paid membership Services through our Website. You acknowledge and accept that by accessing any such paid service that any ancillary terms to that purchase bind you to the terms and conditions already set out here. You acknowledge and agree that when sign up for Agizo’s Services, payments may be processed by third party providers. We are not responsible for any handling fee charged by any third-party provider(s). You agree to hold us harmless for any loss incurred through any third-party processed transactions and or information sharing.' />
					<MainText text='8. Agizo reserves the right, at any time, to amend its fees and/or billing methods as notified on the Website and or by email. Fees are by way of subscriptions (monthly, bi-annually, and annual memberships) and percentage fees as set out in your initial Agreement. Subscriptions are non-refundable. We accept Mobile Money, Credit/Debit Card payments and Cash.' />
					<MainText text='9. You agree and acknowledge that Agizo is not responsible for and will not reimburse any fees incurred by you from your bank or other financial institution, including without limitation overdraft charges, insufficient funds charges, interest charges, or finance charges, which may have occurred because of charges debited or withdrawn by Agizo. If your existing nominated bank account or credit card is cancelled, suspended or is otherwise not usable, you must immediately provide us with details for an alternative nominated bank account or credit card which can be used to meet your obligations under these Terms.' />{' '}
					<MainText text='10. We facilitate the use of M-PESA, Cash and Card payment.' />
				</div>
				<div className='my-6'>
					<p className='font-bold underline'>Suspension / Termination</p>
					<MainText text='11. We value all our Users, but we must reserve the right to suspend access to any User where a User infringes our intellectual property rights; attempts to bypass our security measures; engages in threatening, abusive, or insulting behaviour; provides fraudulent information; or repeatedly violates these Terms.' />
					<MainText text='12. You acknowledge and agree that we may modify, suspend or discontinue (for a reasonable period of time) access to our Website and/or Services, if it is reasonably necessary for us to carry out any maintenance, updates or business operations; and/or modify, limit, suspend or terminate your Account if you breach term 10,11, above.' />
					<MainText text='13. You may cancel your account by providing 30-days’ notice. If you subscribed to a plan that offers a free trial, you may cancel any time before the end of the trial period without incurring any cost. If you cancel your membership after the trial period ends, you will be charged for, and retain access to membership platform until the end of, your current billing cycle. If you did not sign up for membership with a free trial, you are able to cancel your membership at any time, but you will be charged for, and retain access to membership content until the end of, your current billing cycle. Please note that if you cancel your membership after a billing cycle is over, you will not receive a refund for that period. All accounts become inactive following 90-days of inactivity by Users.' />
				</div>
				<div className='my-6'>
					<p className='font-bold underline'>Intellectual Property</p>
					<MainText text='14. Except as provided or as explicitly allowed by us, you may not copy, mirror, download, stream, capture, reproduce, duplicate, archive, upload, modify, translate, publish, broadcast, transmit, retransmit, distribute, perform, display, sell, frame or link, make available, or otherwise use any of our content.' />
					<MainText text='15. You acknowledge and accept that all intellectual property rights (‘IPR’) vested in the content of our Website and software, including but not limited to our platform, functions, source-code, logos, brand names, text, images, and overall look belong to us. Nothing herein extends any form of IPR, licence, or permission to copy, publish, manipulate, reproduce, distribute, or otherwise use in any format, our own content without our express written permission or as express/implied within your Agizo User licence.' />
					<MainText
						text='
16. We shall not be subject to any obligations of confidentiality or privacy regarding submitted information except as specifically agreed or required by law.'
					/>
					<MainText text='17. By using the Website and Services, you grant us an unrestricted, worldwide, royalty-free, sub-licensable licence to use, reproduce, publish, communicate to the public, modify, and adapt any feedback posted on the Website for the purpose of publishing that User Feedback on the Website and as otherwise permitted by this Agreement.' />
					<MainText text='18. We respect the intellectual property of others and require that our Users do the same. We reserve the right to remove or disable access to any transmission of content that infringes the copyright/trademark of any person/business under the laws of Kenya upon receipt of a notice pursuant to the Copyright Act 2001 and or the Trademark Act, or any legislation applicable to any jurisdiction we operate in.' />
				</div>
				<div className='my-6'>
					<p className='font-bold underline'>Liability</p>{' '}
					<MainText
						text='
19. While we aim to ensure accuracy and workability, any material within our Website or part of our Services exist without any guarantee or warranty that it is accurate and or without fault. We shall not be liable for any reliance, implied conditions, warranties, or terms and or be liable for any damages for direct, indirect, consequential, special, or incidental damages or loss arising out of or related to the use of our Website / Services, or the inability to use our Services, irrespective of foreseeability. Further, you acknowledge and accept we disclaim liability for information provided to us and passed on to you/third parties.'
					/>
					<MainText text='20. Our Website and all Services are provided on an “as is” and “as available” basis, and (to the extent permitted by law or as otherwise provided in these Terms) without any warranty or representation of any kind either express or implied; you assume all responsibility in connection with orders; customers; retention of information; and third-parties; and no advice or information, whether oral or written, obtained by you from us through our Website, Services, or otherwise will create any warranty, representation or guarantee not expressly stated in these Terms..' />
					<MainText text='21. You hereby waive any claim arising out of your use of our Website and Services. You agree to hold us harmless for any damage or loss caused by any viruses or other technologically harmful material that may infiltrate your computer programs, data, computer equipment, or other proprietary material due to your use of our platform, Services, or software or by your downloading of any material herein or on any externally linked Website.' />
					<MainText text='22. You agree to indemnify and hold us, our affiliates, subcontractors and other partners, and their respective officers, agents, partners, and employees, harmless from any loss, liability, claim, or demand, including, but not limited to, reasonable legal fees, made by any third party due to or arising out of or in connection with your usage / interaction with our Website/Services.' />
					<MainText
						text='
23. We cannot be held liable for a loss of functionality of any of our Services. By accessing our Services, you hereby accept that we disclaim the fraudulent use by any third parties of Services that may incur loss on any User.
'
					/>
					<MainText
						text='
24. Nothing in these Terms limits any right or obligation that you may have under the Kenyan Consumer Law, including any consumer guarantee or right to refund, or any other right under any law, to the extent that it cannot lawfully be excluded or limited.'
					/>
				</div>
				<div className='my-6'>
					<p className='font-bold underline'>No Waiver</p>{' '}
					<MainText text='25. No failure or delay by us in exercising any right, power, or privilege shall operate as a waiver, nor shall any single or partial exercise of a right preclude us from any other or further exercise of any right, power, or privilege we are entitled to.' />
				</div>
				<div className='my-6'>
					<p className='font-bold underline'>Force Majecure</p>{' '}
					<MainText text='26. We shall not be in default of any obligation if the failure to perform the obligation is due to any event beyond our control, including, without limitation to, any failure of a portion of the power grid, failure of the Internet, any natural disaster, war, riot, insurrection, epidemic, strikes or other organised labour action, terrorist activity, or other events for which precautions are not generally taken in the industry and not reasonably foreseeable.' />
				</div>
				<div className='my-6'>
					<p className='font-bold underline'>Governing Law</p>{' '}
					<MainText text='27. These Terms and the relationship between you and Agizo, will be governed by the laws of Kenya. The parties agree to the non-exclusive jurisdiction of the courts of Kenya.' />
					<MainText
						text='
28. We may report to the appropriate authorities any conduct by a User that we believe violates applicable law and provide any information in response to a formal or informal request from a law enforcement or regulatory agency or in response to a formal request in a civil action.'
					/>
					<div className='my-6'>
						<p className='font-bold underline'>General Terms</p>{' '}
						<MainText text='29. If any portion of these Terms is found to be unenforceable, the remaining portion will remain in full force and effect. Any amendment to or waiver of these Terms must be made in writing and signed by us.' />
						<MainText text='30. These Terms constitutes the entire Agreement between you and Agizo with respect to the access and usage of our Services, and supersedes all prior oral or written understandings, communications or agreements.' />
						<MainText text='31. If for any reason a court holds any provision of these Terms, or portion thereof, to be unenforceable, that Term will be read down to the minimum extent necessary to give full effect to the intent of the parties, and the remainder of our Agreement will continue in full force and effect.' />
					</div>
					<div className='my-6'>
						<p className='font-bold underline'>Acceptable Use Policy</p>{' '}
						<MainText text='32. You agree that you will not:' />
						{acceptableItems.map((item, index) => (
							<SubText text={item} key={index} />
						))}
						<MainText text='33. By using our Services, you agree that you will not publish and or otherwise transmit/offer any content that contains the following substance:' />
						{substance.map((item, index) => (
							<SubText text={item} key={index} />
						))}
					</div>
					<div className='my-8 justify-center'>
						<p className='font-bold tracking-widest text-red-500 uppercase text-center'>
							privacy policy
						</p>
					</div>
					<PolicyItem
						title='Our Scope'
						description='We, Agizo, want you to know how we collect, use and disclose information from you. This Privacy Policy will outline our practices. By using our Website/Services, you agree to the terms and conditions of this Privacy Policy, and those above. We do not knowingly collect personal information from children (those under 18 years of age). Our Privacy Policy applies to all users and the collection/use of your personal information
'
					/>
					<PolicyItem
						title='Collection of Data'
						description='We only collect information that includes, but may not be limited to:
'
					/>
					<PolicyItemN
						title='Your Contact Details'
						description='This allows us to directly identify and or contact you and may include your Name, Address, Age, Images, Phone Numbers, E-mails, Location, and other personal information.'
					/>
					<PolicyItemN
						title='Website Data'
						description='When you use our Website, we collect duration and time of the session, any pages visited, transaction details, and technical info e.g., IP address, MAC address etc.'
					/>
					<PolicyItemN
						title='Customer Care Information'
						description='This means information shared when you contact us inquiring about our Website and or Services. In addition, your support requests and the details required to resolve them. You understand and agree that we may make a record of any issue(s).'
					/>
					<PolicyItem
						title='Use/Disclosure'
						description='We may use information that we collect to provide our Services and associated features to you. You’ll agree these are necessary, inter alia:
'
					/>
					<Numbered item='i. To allow you access and interact with our platform.' />
					<Numbered item='ii. To enable us to respond to your queries effectively.' />
					<Numbered item='iii. To send you relevant content, information, marketing, and updates.' />
					<Numbered item='iv. To process subscriptions.' />
					<Numbered item='v. To help us monitor and improve our Services and quality assurances.' />
					<Numbered item='vi. To allow social sharing functionality.' />
					<Numbered item='vii. To comply with legal obligations.' />
				</div>
				<div className='my-6'>
					<Numbered item='We may be required by law to retain or disclose your information to authorities, including law enforcement bodies. Also, we may retain or share information if we believe it is reasonably necessary to respond to a lawful legal request, protect rights, enforce terms and conditions of our service, and detect or prevent or investigate any illegal activity.' />
				</div>
				<div className='my-6'>
					<Numbered item='We will retain your information for the period necessary to fulfil the purposes outlined in this Privacy Policy unless a longer retention period is required or allowed by law.' />
				</div>
				<div className='my-6'>
					<Numbered item='Please note, you may cancel your account but even if you cancel your account or ask us to delete your personal information, some information from your account may remain viewable if you have shared information with social media or other third-party services.' />
				</div>
				<div className='my-6'>
					<Numbered item='We may also backup your information on secure servers to comply with applicable law or internal security policies. It may not always be possible to completely delete all your information due to legal, technical, or contractual constraints.' />
				</div>
				<div className='my-10'>
					<PolicyItem
						title='User Access'
						description='You can access personal information we hold about you and or delete your information by emailing us here [ admin@agizo.net] . Please note we may ask you to verify your identity. If you wish to do so, please include your email address, name, address, and telephone number and specify clearly what information you would like to delete, access or update and we will try to comply with your request as soon as we can, pursuant to our obligations. You may request we not share your personal information with our affiliates or unaffiliated third parties. We will try to comply with your request as soon as we can, pursuant to our obligations as per Kenya’s Data Protection Act, 2019.
'
					/>
				</div>
				<div className='my-10'>
					<PolicyItem
						title='How we Protect Your Information'
						description='Data is stored in encrypted databases on a private network in a Cloud-based server. We use reasonable measures to safeguard the personal information we hold about you from loss, theft and unauthorised use, disclosure, or modification, including:'
					/>
					{protection.map((item, index) => (
						<div className='mx-10' key={index}>
							<Numbered item={item} />
						</div>
					))}
				</div>
				<div className='my-10'>
					<PolicyItem
						title='Cookies'
						description='Cookies and similar technologies allow small pieces of information to be read from or placed onto your device when you visit a Website or application. We use operational cookies to persist sessions and content.Your web browser sends this information back to our Website so that they can remember preferences. They can also help to ensure that adverts you see online are more relevant to you. The cookies and similar technologies used on our Website fall into four categories: strictly necessary, performance, functional, and targeting. You can control and manage cookies on your device, but these changes will apply to all Websites you visit. It is a term of use of this Website that we collect information to allow us continued functionality.'
					/>
				</div>
				<div className='my-10'>
					<PolicyItemN
						title='Managing Cookies in your Browser'
						description='Usually, a browser will allow you to choose the level of privacy settings you want. You can block all cookies, you can accept all cookies, or pick a setting somewhere in between. Deleting cookies means that any preference settings you have made on a Website will be lost. If you’ve set your preferences to opt out of cookies, this setting will be lost too, as that information is stored in a cookie. Blocking all cookies means functionality on our Websites will be lost, as described above. We don’t recommend turning all cookies off when using our Websites. To reduce your cookie settings at any time, you must use your browser settings to remove any third-party cookies from your previous visit(s).'
					/>
				</div>
				<div className='my-10'>
					<PolicyItemN
						title='(1) Right to Know.'
						description='You have the right to request that we disclose to you the following information:The categories of Personal Information we collected about you during the 12 months prior to your request; the specific pieces of Personal Information we collected about you during that time period; the purpose for collecting or disclosing Personal Information about you; the categories of Personal Information about you that we otherwise shared or disclosed and the categories of third parties with whom we shared or disclosed that Personal Information.To make a request for your Personal Information, please email us. You will need to provide your name and email address, along with other details about your request. You can use an authorized agent to submit a request for your Personal Information; however, please email us to commence this procedure. Please note that, in some instances, we may decline to honour your request, e.g., we cannot verify your identity or an exception to this right applies.'
					/>
				</div>
				<div className='my-10'>
					<PolicyItemN
						title='(2) Right to Request Deletion.'
						description='You have the right to request that we delete Personal Information we collected from you. To make a request for your Personal Information, please email us. You will need to provide your name and email address, along with other details about your request. You can use an authorised agent to submit a request for your Personal Information; however, please email us to commence this procedure. Please note that, in some instances, we may decline to honour your request, e.g., we cannot verify your identity or an exception to this right applies.'
					/>
				</div>
				<div className='my-10'>
					<PolicyItemN
						title='(3) Right to Opt-Out of Sale.'
						description='If you wish to opt out of the sharing of your Personal Information in connection with tailored advertising in desktop and mobile browsers, please email us.'
					/>
				</div>
				<div className='my-10'>
					<PolicyItemN
						title='(4) Right to be Free from Discrimination.'
						description='You have the right to be free from unlawful discrimination for exercising your rights.'
					/>
				</div>
				<div className='my-10'>
					<PolicyItemN
						title='(5) Record Keeping.'
						description='Please email us regarding the requests we processed in the last 12-months.'
					/>
				</div>
			</div>
		</div>
	);
};

export default TermsOfService;
